#%RAML 1.0
title: Aggregator Settings
version: v1
baseUri: http://localhost/mod-erm-usage

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage aggregator settings

types:
  aggregatorSetting: !include schemas/aggregatorsetting.json
  aggregatorSettings: !include ./schemas/aggregatorsettings.json
  errors: !include ./raml-util/schemas/errors.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/aggregator-settings:
  displayName: Aggregator Settings
  type:
    collection:
      exampleCollection: !include ./examples/aggregatorsettings_collection.sample
      exampleItem: !include ./examples/aggregatorsettings.sample
      schemaCollection: aggregatorSettings
      schemaItem: aggregatorSetting
  get:
    is: [
      searchable: {description: "", example: "(label="Server*") and aggregatorConfig.reportRelease="4""},
      orderable: {fieldsList: "label"},
      pageable
    ]
    description: Get all aggregator settings
  post:
    is: [validate]
    description: Post new aggregator settings
  /{id}:
    type:
      collection-item:
        exampleItem: !include ./examples/aggregatorsettings.sample
        schema: aggregatorSetting
    get:
      description: Get one aggregator setting identified by id
    delete:
      description: Delete aggregator setting identified by id
    put:
      description: Put aggregator setting identified by id
    /exportcredentials:
      get:
        description: Get SushiCredentials associated with this aggregator
        responses:
          200:
            description: Ok
            body:
              text/csv:
          500:
            description: Error
            body:
              text/plain:


