#%RAML 1.0
title: Counter Reports
version: v1
baseUri: http://localhost/mod-erm-usage

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage counter reports

types:
  counterReport: !include ./schemas/counterreport.json
  counterReports: !include ./schemas/counterreports.json
  errors: !include ./raml-util/schemas/errors.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml

/counter-reports:
  displayName: Counter Reports
  type:
    collection:
      exampleCollection: !include ./examples/counterreport_collection.sample
      exampleItem: !include ./examples/counterreport.sample
      schemaCollection: counterReports
      schemaItem: counterReport
  get:
    is: [
      searchable: {description: "", example: "active=true sortBy username"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    queryParameters:
        tiny:
            type: boolean
            required: false
            default: false
    description: Get all reports
  post:
    is: [validate]
    description: Post new report
  /{id}:
    type:
      collection-item:
        exampleItem: !include ./examples/counterreport.sample
        schema: counterReport
    get:
      description: Get one report identified by id
    delete:
      description: Delete report identified by id
    put:
      description: Put report identified by id
  /csv:
    /{id}:
      get:
        description: Get the report identified by id as CSV
        responses: 
          200:
            body:
              text/csv:
          500:
            description: Server Error
            body:
              text/plain:
                      