#%RAML 1.0
title: Counter Reports
version: v1
baseUri: http://localhost/mod-erm-usage

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage counter reports

types:
  counterReportData: !include ./schemas/counterReportData.json
  counterReportDataCollection: !include ./schemas/counterReportDataCollection.json
  errors: !include ./raml-util/schemas/errors.schema
  error: !include ./raml-util/schemas/error.schema
  parameters: !include ./raml-util/schemas/parameters.schema
  ../metadata: !include ./raml-util/schemas/metadata.schema

traits:
  orderable: !include ./raml-util/traits/orderable.raml
  pageable: !include ./raml-util/traits/pageable.raml
  searchable: !include ./raml-util/traits/searchable.raml
  language: !include ./raml-util/traits/language.raml
  validate: !include ./raml-util/traits/validation.raml

resourceTypes:
  collection: !include ./raml-util/rtypes/collection.raml
  collection-item: !include ./raml-util/rtypes/item-collection.raml
  get-only: !include ./raml-util/rtypes/get-only.raml
  post-empty-body: !include ./raml-util/rtypes/post-empty-body.raml

/counter-reports:
  displayName: Counter Reports
  type:
    collection:
      exampleCollection: !include ./examples/counterreport_collection.sample
      exampleItem: !include ./examples/counterreport.sample
      schemaCollection: counterReportDataCollection
      schemaItem: counterReportData
  get:
    is: [
      searchable: {description: "", example: "active=true sortBy username"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    queryParameters:
        tiny:
            type: boolean
            required: false
            default: false
    description: Get all reports
  post:
    is: [validate]
    description: Post new report
  /{id}:
    type:
      collection-item:
        exampleItem: !include ./examples/counterreport.sample
        schema: counterReportData
    get:
      description: Get one report identified by id
    delete:
      description: Delete report identified by id
    put:
      description: Put report identified by id