#%RAML 0.8
title: Counter Provider
version: v1
baseUri: http://localhost/mod-erm-usage

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage Counter Providers

schemas:
  - counterProviderData.json: !include ./schemas/counterProviderData.json
  - counterProviderDataCollection.json: !include ./schemas/counterProviderDataCollection.json
  - errors: !include ./raml-util/schemas/errors.schema
  - error.schema: !include ./raml-util/schemas/error.schema
  - parameters.schema: !include ./raml-util/schemas/parameters.schema

traits:
  - secured: !include ./raml-util/traits/auth.raml
  - orderable: !include ./raml-util/traits/orderable.raml
  - pageable: !include ./raml-util/traits/pageable.raml
  - searchable: !include ./raml-util/traits/searchable.raml
  - language: !include ./raml-util/traits/language.raml
  - validate: !include ./raml-util/traits/validation.raml
  - facets: !include ./raml-util/traits/facets.raml

resourceTypes:
  - collection: !include ./raml-util/rtypes/collection.raml
  - collection-item: !include ./raml-util/rtypes/item-collection.raml
  - get-only: !include ./raml-util/rtypes/get-only.raml
  - post-empty-body: !include ./raml-util/rtypes/post-empty-body.raml

/counterproviders:
  displayName: Counter Providers
  type:
    collection:
      exampleCollection: !include ./examples/counterproviders_collection.sample
      exampleItem: !include ./examples/counterproviders.sample
      schemaCollection: counterProviderDataCollection.json
      schemaItem: counterProviderData.json
  get:
    description: Get all Counter providers
  post:
    description: Post new Counter providers
  /{id}:
    type:
      collection-item:
        exampleItem: !include ./examples/counterproviders.sample
        schema: counterProviderData.json
    get:
      description: Get one Counter provider identified by id
    delete:
      description: Delete Counter provider identified by id
    put:
      description: Put Counter provider identified by id