#%RAML 0.8
title: Sushi Settings
version: v1
baseUri: http://localhost/mod-erm-usage

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage Sushi settings

schemas:
  - sushiSettingsData.json: !include schemas/sushiSettingsData.json
  - sushiSettingsDataCollection: !include ./schemas/sushiSettingsDataCollection.json
  - errors: !include ./raml-util/schemas/errors.schema
  - error.schema: !include ./raml-util/schemas/error.schema
  - parameters.schema: !include ./raml-util/schemas/parameters.schema

traits:
  - secured: !include ./raml-util/traits/auth.raml
  - orderable: !include ./raml-util/traits/orderable.raml
  - pageable: !include ./raml-util/traits/pageable.raml
  - searchable: !include ./raml-util/traits/searchable.raml
  - language: !include ./raml-util/traits/language.raml
  - validate: !include ./raml-util/traits/validation.raml
  - facets: !include ./raml-util/traits/facets.raml

resourceTypes:
  - collection: !include ./raml-util/rtypes/collection.raml
  - collection-item: !include ./raml-util/rtypes/item-collection.raml
  - get-only: !include ./raml-util/rtypes/get-only.raml
  - post-empty-body: !include ./raml-util/rtypes/post-empty-body.raml

/sushicreds:
  displayName: Sushi Credentials
  type:
    collection:
      exampleCollection: !include ./examples/sushisettings_collection.sample
      exampleItem: !include ./examples/sushisettings.sample
      schemaCollection: sushiSettingsDataCollection
      schemaItem: sushiSettingsData.json
  get:
    description: Get all Sushi credentials
  post:
    description: Post new Sushi credentials
  /{id}:
    type:
      collection-item:
        exampleItem: !include ./examples/sushisettings.sample
        schema: sushiSettingsData.json
    get:
      description: Get one Sushi credential identified by id
    delete:
      description: Delete Sushi credential identified by id
    put:
      description: Put Sushi credential identified by id