#%RAML 0.8
title: Usage Data Providers
version: v1
baseUri: http://localhost/mod-erm-usage

documentation:
  - title: mod-erm-usage API
    content: This documents the API calls that can be made to query and manage usage data providers

schemas:
  - udProvidersData.json: !include schemas/udProvidersData.json
  - udProvidersDataCollection: !include ./schemas/udProvidersDataCollection.json
  - errors: !include ./raml-util/schemas/errors.schema
  - error.schema: !include ./raml-util/schemas/error.schema
  - parameters.schema: !include ./raml-util/schemas/parameters.schema
  - ../metadata.schema: !include ./raml-util/schemas/metadata.schema

traits:
  - secured: !include ./raml-util/traits/auth.raml
  - orderable: !include ./raml-util/traits/orderable.raml
  - pageable: !include ./raml-util/traits/pageable.raml
  - searchable: !include ./raml-util/traits/searchable.raml
  - language: !include ./raml-util/traits/language.raml
  - validate: !include ./raml-util/traits/validation.raml
  - facets: !include ./raml-util/traits/facets.raml

resourceTypes:
  - collection: !include ./raml-util/rtypes/collection.raml
  - collection-item: !include ./raml-util/rtypes/item-collection.raml
  - get-only: !include ./raml-util/rtypes/get-only.raml
  - post-empty-body: !include ./raml-util/rtypes/post-empty-body.raml

/usage-data-providers:
  displayName: Usage Data Providers
  type:
    collection:
      exampleCollection: !include ./examples/udproviders_collection.sample
      exampleItem: !include ./examples/udproviders.sample
      schemaCollection: udProvidersDataCollection
      schemaItem: udProvidersData.json
  get:
    is: [
      searchable: {description: "", example: "active=true sortBy username"},
      orderable: {fieldsList: "field A, field B"},
      pageable
    ]
    description: Get all usage data providers
  post:
    is: [validate]
    description: Post new usage data providers
  /{id}:
    type:
      collection-item:
        exampleItem: !include ./examples/udproviders.sample
        schema: udProvidersData.json
    get:
      description: Get one usage data provider identified by id
    delete:
      description: Delete an usage data provider identified by id
    put:
      description: Put an usage data provider identified by id